# Generated by Django 3.1.5 on 2021-02-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympicvaxinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='https://google.com'),
        ),
    ]
