# Generated by Django 3.1.5 on 2021-02-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympicvaxinfo', '0002_post_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='siteurl',
        ),
    ]
